import React, { Component } from 'react';
import { FaGithub, FaLinkedin, FaChevronRight, FaCalculator, FaPlus, FaBeer, FaSpinner, FaRegSurprise, FaHeart } from 'react-icons/fa'
import { Link } from 'react-router-dom';
import Typical from 'react-typical'
import {
  BodyPage,
  Title, Subtitle, Container, Profile, PictureBorder, RepositoryList, RepositoryInfos,
  SocialMedias, SocialMedia, RepositoryTitle,
  RepositoryDescription, RepositoryContainer, Footer, Links, LoadingContainer
} from './styles'

import api from '../../services/api'

export default class Main extends Component {
  state = {
    repositories: [
      {
        "id": 246173968,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNDYxNzM5Njg=",
        "name": "brasil-exemplo",
        "full_name": "rcolzani/brasil-exemplo",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/brasil-exemplo",
        "description": "Exemplo de como utilizar o módulo Brasil para consultar a receita federal",
        "fork": true,
        "url": "https://api.github.com/repos/rcolzani/brasil-exemplo",
        "forks_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/brasil-exemplo/deployments",
        "created_at": "2020-03-10T00:47:42Z",
        "updated_at": "2020-03-10T00:47:44Z",
        "pushed_at": "2016-01-26T00:48:53Z",
        "git_url": "git://github.com/rcolzani/brasil-exemplo.git",
        "ssh_url": "git@github.com:rcolzani/brasil-exemplo.git",
        "clone_url": "https://github.com/rcolzani/brasil-exemplo.git",
        "svn_url": "https://github.com/rcolzani/brasil-exemplo",
        "homepage": "http://brasil.gammasoft.com.br",
        "size": 70,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 194573867,
        "node_id": "MDEwOlJlcG9zaXRvcnkxOTQ1NzM4Njc=",
        "name": "desafio-03",
        "full_name": "rcolzani/desafio-03",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/desafio-03",
        "description": "Desafio 01- Conceitos do NodeJS. Criando aplicação do zero utilizando Express.  Essa aplicação será utilizada para armazenar projetos e suas tarefas.",
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/desafio-03",
        "forks_url": "https://api.github.com/repos/rcolzani/desafio-03/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/desafio-03/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/desafio-03/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/desafio-03/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/desafio-03/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/desafio-03/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/desafio-03/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/desafio-03/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/desafio-03/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/desafio-03/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/desafio-03/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/desafio-03/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/desafio-03/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/desafio-03/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/desafio-03/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/desafio-03/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/desafio-03/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/desafio-03/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/desafio-03/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/desafio-03/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/desafio-03/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/desafio-03/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/desafio-03/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/desafio-03/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/desafio-03/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/desafio-03/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/desafio-03/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/desafio-03/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/desafio-03/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/desafio-03/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/desafio-03/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/desafio-03/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/desafio-03/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/desafio-03/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/desafio-03/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/desafio-03/deployments",
        "created_at": "2019-07-01T00:18:58Z",
        "updated_at": "2019-09-04T23:56:29Z",
        "pushed_at": "2019-07-01T01:15:41Z",
        "git_url": "git://github.com/rcolzani/desafio-03.git",
        "ssh_url": "git@github.com:rcolzani/desafio-03.git",
        "clone_url": "https://github.com/rcolzani/desafio-03.git",
        "svn_url": "https://github.com/rcolzani/desafio-03",
        "homepage": "",
        "size": 32,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 195133748,
        "node_id": "MDEwOlJlcG9zaXRvcnkxOTUxMzM3NDg=",
        "name": "gobarber-backend",
        "full_name": "rcolzani/gobarber-backend",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/gobarber-backend",
        "description": "Back-end da aplicação GoBarber.",
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/gobarber-backend",
        "forks_url": "https://api.github.com/repos/rcolzani/gobarber-backend/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/gobarber-backend/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/gobarber-backend/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/gobarber-backend/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/gobarber-backend/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/gobarber-backend/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/gobarber-backend/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/gobarber-backend/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/gobarber-backend/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/gobarber-backend/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/gobarber-backend/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/gobarber-backend/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/gobarber-backend/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/gobarber-backend/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/gobarber-backend/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/gobarber-backend/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/gobarber-backend/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/gobarber-backend/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/gobarber-backend/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/gobarber-backend/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/gobarber-backend/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/gobarber-backend/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/gobarber-backend/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/gobarber-backend/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/gobarber-backend/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/gobarber-backend/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/gobarber-backend/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/gobarber-backend/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/gobarber-backend/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/gobarber-backend/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/gobarber-backend/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/gobarber-backend/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/gobarber-backend/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/gobarber-backend/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/gobarber-backend/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/gobarber-backend/deployments",
        "created_at": "2019-07-03T22:25:29Z",
        "updated_at": "2019-08-23T10:08:11Z",
        "pushed_at": "2020-03-15T10:37:58Z",
        "git_url": "git://github.com/rcolzani/gobarber-backend.git",
        "ssh_url": "git@github.com:rcolzani/gobarber-backend.git",
        "clone_url": "https://github.com/rcolzani/gobarber-backend.git",
        "svn_url": "https://github.com/rcolzani/gobarber-backend",
        "homepage": null,
        "size": 628,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 3,
        "license": null,
        "forks": 0,
        "open_issues": 3,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 206446204,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMDY0NDYyMDQ=",
        "name": "meetapp-backend",
        "full_name": "rcolzani/meetapp-backend",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/meetapp-backend",
        "description": "Backend do Meetapp desenvolvido em Node para o Bootcamp da RocketSeat",
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/meetapp-backend",
        "forks_url": "https://api.github.com/repos/rcolzani/meetapp-backend/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/meetapp-backend/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/meetapp-backend/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/meetapp-backend/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/meetapp-backend/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/meetapp-backend/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/meetapp-backend/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/meetapp-backend/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/meetapp-backend/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/meetapp-backend/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/meetapp-backend/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/meetapp-backend/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/meetapp-backend/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/meetapp-backend/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/meetapp-backend/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/meetapp-backend/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/meetapp-backend/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/meetapp-backend/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/meetapp-backend/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/meetapp-backend/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/meetapp-backend/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/meetapp-backend/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/meetapp-backend/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/meetapp-backend/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/meetapp-backend/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/meetapp-backend/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/meetapp-backend/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/meetapp-backend/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/meetapp-backend/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/meetapp-backend/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/meetapp-backend/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/meetapp-backend/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/meetapp-backend/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/meetapp-backend/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/meetapp-backend/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/meetapp-backend/deployments",
        "created_at": "2019-09-05T01:15:23Z",
        "updated_at": "2019-09-06T12:29:36Z",
        "pushed_at": "2019-12-29T22:28:30Z",
        "git_url": "git://github.com/rcolzani/meetapp-backend.git",
        "ssh_url": "git@github.com:rcolzani/meetapp-backend.git",
        "clone_url": "https://github.com/rcolzani/meetapp-backend.git",
        "svn_url": "https://github.com/rcolzani/meetapp-backend",
        "homepage": "",
        "size": 682,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "forks": 0,
        "open_issues": 2,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 224064206,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMjQwNjQyMDY=",
        "name": "react-native-gitapi",
        "full_name": "rcolzani/react-native-gitapi",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/react-native-gitapi",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/react-native-gitapi",
        "forks_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/react-native-gitapi/deployments",
        "created_at": "2019-11-25T23:59:05Z",
        "updated_at": "2019-11-26T23:50:24Z",
        "pushed_at": "2020-03-14T14:34:18Z",
        "git_url": "git://github.com/rcolzani/react-native-gitapi.git",
        "ssh_url": "git@github.com:rcolzani/react-native-gitapi.git",
        "clone_url": "https://github.com/rcolzani/react-native-gitapi.git",
        "svn_url": "https://github.com/rcolzani/react-native-gitapi",
        "homepage": null,
        "size": 391,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 212702309,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMTI3MDIzMDk=",
        "name": "reactjs-api-github",
        "full_name": "rcolzani/reactjs-api-github",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/reactjs-api-github",
        "description": "Aplicação em ReactJS que consumirá a API do Github",
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/reactjs-api-github",
        "forks_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/reactjs-api-github/deployments",
        "created_at": "2019-10-03T23:45:35Z",
        "updated_at": "2020-03-21T20:43:47Z",
        "pushed_at": "2020-03-21T20:43:44Z",
        "git_url": "git://github.com/rcolzani/reactjs-api-github.git",
        "ssh_url": "git@github.com:rcolzani/reactjs-api-github.git",
        "clone_url": "https://github.com/rcolzani/reactjs-api-github.git",
        "svn_url": "https://github.com/rcolzani/reactjs-api-github",
        "homepage": null,
        "size": 590,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "forks": 0,
        "open_issues": 2,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 234430979,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMzQ0MzA5Nzk=",
        "name": "rocketshoes-reactjs",
        "full_name": "rcolzani/rocketshoes-reactjs",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/rocketshoes-reactjs",
        "description": "Rocketshoes with redux, reactotron and toastify",
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs",
        "forks_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactjs/deployments",
        "created_at": "2020-01-16T23:22:54Z",
        "updated_at": "2020-01-16T23:24:13Z",
        "pushed_at": "2020-03-14T23:29:02Z",
        "git_url": "git://github.com/rcolzani/rocketshoes-reactjs.git",
        "ssh_url": "git@github.com:rcolzani/rocketshoes-reactjs.git",
        "clone_url": "https://github.com/rcolzani/rocketshoes-reactjs.git",
        "svn_url": "https://github.com/rcolzani/rocketshoes-reactjs",
        "homepage": null,
        "size": 425,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 246151846,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNDYxNTE4NDY=",
        "name": "rocketshoes-reactnative",
        "full_name": "rcolzani/rocketshoes-reactnative",
        "private": false,
        "owner": {
          "login": "rcolzani",
          "id": 6742811,
          "node_id": "MDQ6VXNlcjY3NDI4MTE=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6742811?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rcolzani",
          "html_url": "https://github.com/rcolzani",
          "followers_url": "https://api.github.com/users/rcolzani/followers",
          "following_url": "https://api.github.com/users/rcolzani/following{/other_user}",
          "gists_url": "https://api.github.com/users/rcolzani/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rcolzani/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rcolzani/subscriptions",
          "organizations_url": "https://api.github.com/users/rcolzani/orgs",
          "repos_url": "https://api.github.com/users/rcolzani/repos",
          "events_url": "https://api.github.com/users/rcolzani/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rcolzani/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rcolzani/rocketshoes-reactnative",
        "description": "Rocketshoes. Meu primeiro aplicativo em react-native com redux e redux saga.",
        "fork": false,
        "url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative",
        "forks_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/forks",
        "keys_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/teams",
        "hooks_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/hooks",
        "issue_events_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/events",
        "assignees_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/tags",
        "blobs_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/languages",
        "stargazers_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/stargazers",
        "contributors_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/contributors",
        "subscribers_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/subscribers",
        "subscription_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/subscription",
        "commits_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/merges",
        "archive_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/downloads",
        "issues_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/labels{/name}",
        "releases_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rcolzani/rocketshoes-reactnative/deployments",
        "created_at": "2020-03-09T22:08:01Z",
        "updated_at": "2020-03-17T00:00:21Z",
        "pushed_at": "2020-03-17T00:00:19Z",
        "git_url": "git://github.com/rcolzani/rocketshoes-reactnative.git",
        "ssh_url": "git@github.com:rcolzani/rocketshoes-reactnative.git",
        "clone_url": "https://github.com/rcolzani/rocketshoes-reactnative.git",
        "svn_url": "https://github.com/rcolzani/rocketshoes-reactnative",
        "homepage": "",
        "size": 785,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      }
    ],
    colorRnd: '#00b386',
    easterEggCounter: 0,
    profilePicture: 'https://avatars1.githubusercontent.com/u/6742811?s=400&u=08e0915ca288e05e885b4bde2193c5cc23d763c9&v=4'
  };

  async componentDidMount() {
    this.setState({ repositories: [] });

    const response = await api.get('/users/rcolzani/repos?sort=updated&direction=desc');

    if (response) {
      this.setState({
        repositories: response.data.sort((a, b) => a.updated_at < b.updated_at).slice(0, 5)
      })
    }
    this.myInterval = setInterval(() => {
      this.setState({ colorRnd: this.randomColor() });
    }, 7000)

  }

  async _onMouseMove(e) {
    // this.setState({ colorRnd: this.randomColor() });
  }

  getIntegerRandom() {
    const min = Math.ceil(0);
    const max = Math.floor(255);
    return Math.floor(Math.random() * (max - min)) + min;
  }

  componentToHex(c) {
    var hex = c.toString(16);
    return hex.length === 1 ? "0" + hex : hex;
  }

  randomColor() {
    return "#" + this.componentToHex(this.getIntegerRandom()) + this.componentToHex(this.getIntegerRandom()) + this.componentToHex(this.getIntegerRandom());
  }

  render() {
    const { repositories, easterEggCounter } = this.state;

    return (
      <BodyPage colorRnd={this.state.colorRnd}>
        <Container className="App"  >
          <Profile>
            <PictureBorder colorRnd={this.state.colorRnd} onClick={() => this.setState({ easterEggCounter: easterEggCounter + 1 })}>
              <img alt="Foto perfil do Github" src={this.state.profilePicture} />
            </PictureBorder>
            <Title colorRnd={this.state.colorRnd}>Ricardo Colzani</Title>
            <Subtitle>Apaixonado por tecnologia <FaHeart color={this.state.colorRnd} /> e desenvolvedor de soluções: VB.net, JavaScript, CSS, ReactJS, React Native, NodeJS...

          </Subtitle>
            <SocialMedias>
              <SocialMedia href="https://www.linkedin.com/in/ricardocolzani/">
                <FaLinkedin />
                <span>/ricardocolzani</span>
              </SocialMedia>
              <SocialMedia href="https://github.com/rcolzani">
                <FaGithub />
                <span>/rcolzani</span>
              </SocialMedia>
            </SocialMedias>
          </Profile>
          <RepositoryContainer>
            <span>Últimos 5 repositórios atualizados</span>
            {repositories.length > 0 ?
              <RepositoryList colorRnd={this.state.colorRnd}>
                {repositories.map(repository => (
                  <li key={repository.name}>
                    <RepositoryInfos>
                      <RepositoryTitle>{repository.name}</RepositoryTitle>
                      <RepositoryDescription>{new Date(repository.updated_at).toLocaleDateString('pt-BR', { dateStyle: "short" })}</RepositoryDescription>
                    </RepositoryInfos>
                    <a href={repository.html_url}>Acessar <FaChevronRight /> </a>
                  </li>
                ))}
              </RepositoryList>
              : <LoadingContainer>
                <span id="loadingrepos">Buscando repositórios no Github <FaSpinner color={this.state.colorRnd} size={50} /></span>
                <Typical steps={[
                  'Esta busca é bem rápida 😁', 2000,
                  'Ué, deve ter algum problema 🤔', 2000,
                  'Não consegui alcançar a API do Github. Mas você pode acessar através do botão que tem ali em cima ☝', 2000
                ]}
                />
              </LoadingContainer>}
          </RepositoryContainer>
        </Container>
        {easterEggCounter >= 10 &&
          <Footer>
            <span>Surpriseeee!!! <FaRegSurprise size={35} /></span>
            <Links>
              <Link to="/calculator">
                <div><FaCalculator /><FaPlus /><FaBeer /></div>
                <span>Calculador CxB</span>
              </Link>
            </Links>

          </Footer>
        }
      </BodyPage>
    );
  }
}

